[project]
name = "mqboost"
version = "1.0.2"
description = "Monotonic composite quantile gradient boost regressor"
readme = "README.md"
authors = [
    {name = "RektPunk", email = "rektpunk@gmail.com"},
]
requires-python = ">=3.10"
classifiers = [
    "Topic :: Software Development :: Libraries :: Python Modules"
]
dependencies = [
    "lightgbm>=4.6.0",
    "numpy>=2.0.2",
    "pandas>=2.3.3",
    "xgboost>=2.1.4",
]

[project.urls]
repository = "https://github.com/RektPunk/MQBoost"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
]

[tool.ruff.lint]
select = ["B", "E", "F", "I", "UP", "SIM"]
ignore = ["E501", "TRY003"]
