name: Lint

on:
  push:
    paths:
      - "**.py"
      - "**.ipynb"

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6

      - name: Install Ruff
        uses: astral-sh/ruff-action@v4.0.0
        with:
          args: "--version"

      - name: Run Ruff Check & Format
        run: |
          ruff check .
          ruff format --check --diff .
