name: Lint

on:
  push:
    paths:
      - "**.py"

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6

      - name: Lint with Ruff
        uses: astral-sh/ruff-action@v4
        with:
          args: "check . && ruff format --check --diff ."
